#!/bin/bash
#SBATCH --job-name="wave"
#SBATCH --ntasks=192
#SBATCH --time=01:00:00
#SBATCH --workdir=.
#SBATCH --output=wave_%j.out
#SBATCH --error=wave_%j.err

module load intel
module load impi
module load hdf5

SCRATCH=/gpfs/scratch/nct00/$USER/$SLURM_JOBID
SUBMDIR=$PWD

mkdir -p $SCRATCH || exit 1

cp wave      $SCRATCH
cp h2anim.pl $SCRATCH 

cd $SCRATCH 

# grid definition

# grid-size in x and y-direction
m=200 
n=200

# mesh size
dx=1.0
dy=1.0

# time step
dt=0.01

# wave propagation speed
c=0.3

# damping
zeta=0.0

# number of time steps, output interval
nt=100000
nt_i=1000


# initial condition: a cosine bump around (f0x0,f0y0) with radius f0r0
f0x0=50.0
f0y0=100.0
f0r0=20.0

outfile=wave.h5


# if wave was compiled with OpenMPI support, set the number of threads
# export OMP_NUM_THREADS=4

srun \
  ./wave $m $n $dx $dy $nt $dt $c $zeta $f0x0 $f0y0 $f0r0 $nt_i $outfile

perl h52anim.pl wave.h5 u

cp wave.h5 wave.h5.gif $SUBMDIR
